# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170126_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video1',
            new_name='Video',
        ),
    ]
